spring:
  application:
    name: activity-service
  mongodb:
    uri: mongodb://localhost:27017/
    database: fitness_activitydb

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

